# Generated by Django 3.2.3 on 2021-07-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneda',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='ID Moneda'),
        ),
    ]
