# Generated by Django 3.2.3 on 2021-07-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_moneda_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='E-mail'),
        ),
    ]
